# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  torneodetenis:
    image: torneodetenis
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5292:5292
