# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  torneo-de-tenis-webapi:
    image: torneo-de-tenis-webapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5292:5292
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - torneo-de-tenis-db
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  torneo-de-tenis-db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql
    environment:
      - SA_PASSWORD=********
      - ACCEPT_EULA=Y

volumes:
  sql-server-data:
